config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  root 'sounds#index'

  resources :sounds

  get '/sound/:id/share' => 'sounds#share', as: 'share_sound'
  resources :authorizations, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  belongs_to :sound

  validates :sound, uniqueness: { scope: :user, message: "can only be authorized once per user." }

  delegate :full_name, to: :user
end

app/models/sound.rb
class Sound < ActiveRecord::Base
  attachment :audio, extension: ["mp3", "mp4", "m4a", "aif", "wav"]
  belongs_to :owner, class_name: "User", foreign_key: :user_id
  has_many :authorizations, dependent: :destroy
  has_many :authorized_users, through: :authorizations, source: :user

  validates :audio, :owner, presence: true
  validates :audio_id, uniqueness: true

  scope :public_share, -> { where(public: true).order(created_at: :desc) }

  self.per_page = 10

  def title
    return name unless name.blank?
    "Sound from #{ created_at.strftime "%A, %B %d" }"
  end

  def owned_by?(user)
    owner == user
  end

  def authorized_to?(user)
    authorized_users.include?(user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :sounds, dependent: :destroy
  has_many :authorizations
  has_many :authorized_sounds, -> { distinct }, through: :authorizations, source: :sound

  validates :password, confirmation: true

  self.per_page = 10

  def full_name
    if first_name.blank? && last_name.blank?
      email
    else
      "#{first_name} #{last_name}"
    end
  end

  def sound_feed
    authorized_ids = "SELECT sound_id FROM authorizations WHERE user_id = :user_id"
    Sound.where("id IN (#{authorized_ids}) OR user_id = :user_id OR public = true", user_id: id).order(created_at: :desc)
  end

  def sounds_by(owner)
    authorized_ids = "SELECT sound_id FROM authorizations INNER JOIN sounds ON (authorizations.sound_id = sounds.id) WHERE sounds.user_id = :owner_id AND authorizations.user_id = :user_id"
    Sound.distinct.where("user_id = :owner_id AND (id IN (#{authorized_ids}) OR public = true)", user_id: id, owner_id: owner.id).order(created_at: :desc)
  end

  def public_sound_count
    sounds.where(public: true).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  def create
    @sound = Sound.find(params[:authorizations][:sound_id])
    authorize @sound, :share?
    user_ids = params[:authorizations][:user_ids].reject { |item| @sound.authorized_users.ids.map(&:to_s).include? item }
    users = User.find(user_ids)
    @sound.authorized_users << users
    redirect_to @sound
  end

  def destroy
    @authorization = Authorization.find(params[:id])
    authorize(@authorization)
    @authorization.destroy
    redirect_to @authorization.sound
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < Clearance::PasswordsController
  skip_after_action :verify_authorized
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  skip_after_action :verify_authorized
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  skip_after_action :verify_policy_scoped, only: [:index]

  def index
    if signed_in?
      @sounds = current_user.sound_feed.paginate(page: params[:page])
    else
      @sounds = Sound.public_share.paginate(page: params[:page])
    end
  end

  def new
    @sound = current_user.sounds.build
    authorize @sound
  end

  def create
    @sound = current_user.sounds.build sound_params
    authorize @sound

    if @sound.save
      flash[:success] = "Sound has been saved."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @sound = Sound.find params[:id]
    authorize @sound
    @authorizations = @sound.authorizations if @sound.owned_by?(current_user)
  end

  def edit
    @sound = Sound.find params[:id]
    authorize @sound
  end

  def update
    @sound = Sound.find params[:id]
    authorize @sound

    if @sound.update sound_params
      flash[:success] = "Sound updated."
      redirect_to @sound
    else
      render :edit
    end
  end

  def destroy
    @sound = Sound.find params[:id]
    authorize @sound

    if @sound.destroy
      flash[:success] = "Sound deleted."
      redirect_to root_path
    else
      flash[:danger] = "Sound could not be deleted."
      redirect_to @sound
    end
  end

  def share
    @sound = Sound.find params[:id]
    authorize @sound
    @users = User.where.not(id: current_user.id)
  end

  private

  def sound_params
    params.require(:sound).permit(:name, :audio, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  skip_after_action :verify_authorized, only: [:new, :create]

  def index
    @users = policy_scope(User.order(last_name: :asc).paginate(page: params[:page]))
  end

  def show
    @user = User.find(params[:id])
    authorize @user

    if current_user == @user
      @sounds = @user.sounds.order(created_at: :desc)
    elsif signed_in?
      @sounds = current_user.sounds_by(@user)
    else
      @sounds = @user.sounds.public_share
    end
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    params[:user].delete :password
    params[:user].delete :password_confirmation

    unless params[:user][:new_password].blank?
      if @user.authenticated? params[:user][:current_password]
        params[:user][:password] = params[:user][:new_password]
        params[:user][:password_confirmation] = params[:user][:new_password_confirmation]
      else
        flash[:alert] = "Please check your password and try again."
        redirect_to(edit_user_path(@user)) and return
      end
    end

    if @user.update user_params
      flash[:success] = "Account updated successfully."
      redirect_to edit_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user

    if @user.destroy
      flash[:success] = "Your account has been deleted."
      redirect_to root_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def user_from_params
    params[:user] ? User.new(user_params) : User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundShare</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="application">
  <div class="container-fluid">
    <%= render 'shared/navbar' %>
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-#{name}" %>
    <% end %>

    <%= yield %>

    <footer>
      <p>Created by <%= link_to "Hugh Middleton", "//hughfm.com" %> for testing and evaluation purposes only.</p>
      <%= debug(params) if Rails.env.development? %>
    </footer>
  </div>
</div>
</body>
</html>

app/views/session/_form.html.erb
<%= form_for :session, url: login_path do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <%= f.submit "Log in", class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/session/new.html.erb
<div class="row">
  <div class="col-sm-5">
    <h1>log in</h1>
  </div>
  <div class="col-sm-7">
    <%= render partial: 'form' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="error-explanation">
    <p>Please correct the following <%= pluralize object.errors.count, "problem" %>:</p>
  </div>
  <div class="errors">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="/">SoundShare</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">
    <ul class="nav navbar-nav navbar-left">
      <% if signed_in? %>
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><%= link_to 'Upload Sound', new_sound_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Sounds", current_user %></li>
            <li><%= link_to 'Account Details', edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to t('layouts.application.sign_out'), sign_out_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t('layouts.application.sign_up'), sign_up_path %></li>
        <li><%= link_to t('layouts.application.sign_in'), sign_in_path %></li>
      <% end %>
    </ul>
    <!-- <form class="navbar-form navbar-right" action="#" role="search">
      <div class="form-group">
        <div class="input-group">
          <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
          <span class="input-group-btn">
            <button type="submit" class="btn"><span class="fui-search"></span></button>
          </span>
        </div>
      </div>
    </form> -->
  </div><!-- /.navbar-collapse -->
</nav><!-- /navbar -->

app/views/shared/_tags.html.erb
<%= content_tag(:span, "Public", class: "label label-default") if sound.public? %>
<%= content_tag(:span, "Shared with me", class: "label label-default") if sound.authorized_users.include?(current_user) %>
<%= content_tag(:span, "My Sound", class: "label label-default") if sound.owned_by?(current_user) %>

app/views/sounds/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'sounds/waveform' %>
  <%= javascript_include_tag 'sounds/form' %>
<% end %>


<%= form_for @sound do |f| %>
  <%= render partial: 'shared/errors', locals: { object: @sound } %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :audio, "Audio File" %>
    <%= f.attachment_field :audio, direct: true, presigned: true %>
    <progress value="0" max="100"></progress>
    <p id="file-name"></p>
  </div>

  <div class="form-group">
    <%= f.label :public %>
    <%= f.check_box :public %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/sounds/_share.html.erb
<span class="label label-default share"><%= link_to content_tag(:span, "", class: "fui-cross-circle"), authorization, method: :delete %>
<%= link_to authorization.full_name, authorization.user %></span>

app/views/sounds/_sound.html.erb
<div>
  <div class="row">
    <div class="col-sm-8">
      <h6><span class="fui-mic side-buffers"></span><%= link_to sound.title, sound %></h6>
      <p><small>Uploaded by <%= link_to sound.owner.full_name, sound.owner %> on <%= sound.created_at.strftime "%A %d %B" %></small></p>
    </div>
    <div class="col-sm-4 top-buffer">
      <%= render partial: 'shared/tags', locals: { sound: sound } %>
    </div>
  </div>
</div>

app/views/sounds/_waveform.html.erb
<div id="wavesurfer">
  <div id="waveform" <%= "data-url= #{attachment_url(sound, :audio)}" if sound.audio %>>
      <div class="progress progress-striped active" id="progress-bar">
          <div class="progress-bar progress-bar-info"></div>
      </div>
      <!-- Here be the waveform -->
  </div>

  <div class="text-center">
    <div class="controls btn-group">
        <button class="btn btn-primary" data-action="back" disabled>
            <i class="glyphicon glyphicon-step-backward"></i>
        </button>

        <button class="btn btn-primary" data-action="play" disabled>
            <i class="glyphicon glyphicon-play"></i>
            /
            <i class="glyphicon glyphicon-pause"></i>
        </button>

        <button class="btn btn-primary" data-action="forth" disabled>
            <i class="glyphicon glyphicon-step-forward"></i>
        </button>

        <button class="btn btn-primary" data-action="toggle-mute" disabled>
            <i class="glyphicon glyphicon-volume-off"></i>
        </button>
    </div>
  </div>
</div>

app/views/sounds/edit.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'sounds/waveform' %>
  <%= javascript_include_tag 'sounds/show' %>
<% end %>

<div class="row">
  <div class="col-sm-5">
    <h1>edit sound</h1>
  </div>
  <div class="col-sm-7">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 top-buffer">
    <p>Preview</p>
    <%= render partial: 'waveform', locals: { sound: @sound } %>
  </div>
</div>

app/views/sounds/index.html.erb
<h1>feed</h1>

<div class="list top-buffer-lg">
  <%= render @sounds %>
</div>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/sounds/new.html.erb
<div class="row">
  <div class="col-sm-5">
    <h1>upload a new sound</h1>
  </div>
  <div class="col-sm-7">
    <%= render 'form' %>

  </div>
</div>

<div class="row">
  <div class="col-sm-12 top-buffer">
    <p>Preview</p>
    <%= render partial: 'waveform', locals: { sound: @sound } %>
  </div>
</div>

app/views/sounds/share.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'users/share' %>
<% end %>

<div class="row">
  <div class="col-sm-4">
    <h3><%= link_to @sound.name, @sound %></h3>
  </div>
  <div class="col-sm-8">
    <h4>share with: </h4>
      <%= form_for :authorizations, url: authorizations_path do |f| %>
        <%= f.hidden_field :sound_id, value: @sound.id %>
        <%= f.collection_select(:user_ids, @users, :id, :full_name, { include_hidden: false, selected: @sound.authorized_users.ids }, { multiple: "multiple", class: "form-control multiselect multiselect-info" }) %>
        <%= f.submit "Share", class: "btn btn-lg btn-primary top-buffer" %>
      <% end %>
  </div>
</div>

app/views/sounds/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'sounds/waveform' %>
  <%= javascript_include_tag 'sounds/show' %>
<% end %>

<div class="row">
  <div class="col-sm-4">
    <h3><%= @sound.title %></h3>
    <div>
      <%= render partial: 'shared/tags', locals: { sound: @sound } %>
    </div>
    <div class="top-buffer-lg">
      <% if @authorizations && @authorizations.any? %>
        <p>Sharing with:</p>
        <div>
          <% @authorizations.each do |authorization| %>
            <%= render partial: 'share', locals: { authorization: authorization } %>
          <% end %>
        </div>
      <% end %>
    </div>
    <p>
      <% unless @sound.owned_by?(current_user) %>
        Uploaded by: <%= link_to(@sound.owner.full_name, @sound.owner) %>
      <% end %>
    </p>
  </div>
  <div class="col-sm-8 top-buffer">
    <%= render partial: 'waveform', locals: { sound: @sound } %>
  </div>
</div>

<% if @sound.owned_by?(current_user) %>
  <div class="row">
    <div class="col-sm-12 top-buffer">
      <div class="text-center top-buffer">
        <div class="btn-group">
          <%= link_to 'share', share_sound_path(@sound), class: "btn btn-lg btn-inverse" %>
          <%= link_to 'edit', edit_sound_path(@sound), class: "btn btn-lg btn-primary" %>
          <%= link_to 'delete', @sound, method: :delete, class: "btn btn-lg btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_account_fields.html.erb
<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :current_password, "Current Password (required if changing password)" %>
  <%= f.password_field :current_password, class: "form-control" %>

  <%= f.label :new_password, "New Password (leave blank if unchanged)" %>
  <%= f.password_field :new_password, class: "form-control" %>

  <%= f.label :new_password_confirmation %>
  <%= f.password_field :new_password_confirmation, class: "form-control" %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render partial: 'shared/errors', locals: { object: @user } %>

  <%= render partial: "users/#{fields}", locals: { f: f } %>

  <%= f.submit action, class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/users/_signup_fields.html.erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-sm-12">
    <div>
      <span class="fui-user side-buffers"></span>
      <%= link_to user.full_name, user %>
    </div>
    <div class="top-buffer">
      <p><span class="fui-mic side-buffers"></span> <%= user.public_sound_count %></p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>edit account details</h1>
<div class="row">
  <div class="col-sm-7">
    <%= render partial: 'form', locals: { action: "Save Changes", fields: "account_fields" } %>
  </div>
  <div class="col-sm-5">
    <div class="row top-buffer">
      <div class="col-sm-12">
        <%= link_to 'Cancel', @user, class: "btn btn-lg btn-default btn-block" %>
      </div>
    </div>
    <div class="row top-buffer">
      <div class="col-sm-12">
        <%= link_to 'Delete Account', @user, data: { method: :delete, confirm: 'Are you sure?' }, class: "btn btn-lg btn-danger btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>listing all users</h1>

<div class="list top-buffer-lg">
  <%= render @users %>
</div>

<div class="text-center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-5">
    <h1>create an account</h1>
  </div>

  <div class="col-sm-7">

    <%= render partial: 'users/form', locals: { action: t('helpers.submit.user.create'), fields: "signup_fields" } %>

  </div>
</div>

app/views/users/show.html.erb
<h2>sounds by <%= content_tag :span, @user.full_name %></h2>

<p><%= @user.email %></p>

<%= render @sounds %>